# Numpy Tutorial 

In [1]:
import numpy as np

In [2]:
# one dimensional array
myarr = np.array([3,6,32,7],np.int8)

In [3]:
myarr

array([ 3,  6, 32,  7], dtype=int8)

In [4]:
myarr[2]

32

In [5]:
# 2-D array
myarr2 = np.array([[2,5,7,88]])

In [6]:
myarr2[0,2]

7

In [7]:
# it will give dtype of array
myarr2.dtype

dtype('int32')

In [8]:
myarr2.shape

(1, 4)

In [9]:
# can change the value at any index
myarr2[0,2]=4585

In [10]:
myarr2

array([[   2,    5, 4585,   88]])

# Array Creation Using Different Methods : 

In [11]:
# Array creation using tuple
tup = (1,25,68,45,)
tarr = np.array(tup)

In [12]:
tarr

array([ 1, 25, 68, 45])

In [13]:
# array creation using arange func
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
# array creation using arange func
arr1 = np.arange(90,100,2)
arr1

array([90, 92, 94, 96, 98])

In [15]:
# array creation using linspace func
arr2 = np.linspace(90,100,8)
arr2

array([ 90.        ,  91.42857143,  92.85714286,  94.28571429,
        95.71428571,  97.14285714,  98.57142857, 100.        ])

In [16]:
# empty array of random elements of order 4x5
emp = np.empty([4,5])
emp

array([[6.23042070e-307, 1.42417221e-306, 1.37961641e-306,
        9.45695435e-308, 1.11258854e-306],
       [1.11261502e-306, 1.42410839e-306, 7.56597770e-307,
        6.23059726e-307, 1.42419530e-306],
       [1.37961302e-306, 1.78019082e-306, 1.11260144e-306,
        6.89812281e-307, 1.42418172e-306],
       [8.06610070e-308, 6.89810244e-307, 1.22387550e-307,
        2.22522596e-306, 4.94065646e-322]])

In [17]:
# empty array of same order of arr2
empty_like = np.empty_like(arr2)
empty_like

array([ 90.        ,  91.42857143,  92.85714286,  94.28571429,
        95.71428571,  97.14285714,  98.57142857, 100.        ])

In [18]:
nat = np.arange(99)
nat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [19]:
# reshaping
renat = nat.reshape(3,33)
renat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [20]:
# .ravel() , make any array to 1 - D
renat.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [21]:
# array creation using ones func
one = np.ones([2,3])
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# array creation using zeros func
zero = np.zeros([2,3])
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# array creation using diag func
dia = np.diag([1,2,3])
dia

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [24]:
# identity array creation using eye func
idt = np.eye(3)
idt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# identity array creation using eye func
idt = np.eye(2,3)
idt

array([[1., 0., 0.],
       [0., 1., 0.]])

In [26]:
'''Vandermonde matrix is a decreasing power of 
the input 1D array or list or tuple, x where the 
highest polynomial order is n-1. '''
van = np.vander((1, 2, 3, 4), 4)
van

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [27]:
import pandas as pd
df = pd.DataFrame(van,index = [1,2,3,4],columns= [ 'n^3','n^2','n^1','n^0'])
df

n^3  n^2  n^1  n^0
1    1    1    1    1
2    8    4    2    1
3   27    9    3    1
4   64   16    4    1

In [28]:
van.shape

(4, 4)

In [29]:
van.size

16

# NumPy Axis and Some methods & Attributes

In [30]:
x = [[1,2,3,],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [31]:
# sum in axis=0 i.e. in columns
ar.sum(axis=0)

array([12,  8,  9])

In [32]:
# sum in axis=1 i.e. in rows
ar.sum(axis=1)

array([ 6, 15,  8])

In [33]:
# .T make a transpose
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [34]:
ar.flat
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [35]:
ar.ndim

2

In [36]:
ar.size

9

In [37]:
ar.nbytes  # .nbytes give the total no of bytes consumed

36

In [38]:
one = np.array([1,3,4,634,2])
one

array([  1,   3,   4, 634,   2])

In [39]:
# .argmax() gives max element index 
one.argmax()

3

In [40]:
# .argmin() gives min element index 
one.argmin()

0

In [41]:
two = np.array([[1,7,4,643,2],[12,5,9,6,9]])
two

array([[  1,   7,   4, 643,   2],
       [ 12,   5,   9,   6,   9]])

In [42]:
# .argmax() gives max element index in a particular axis
two.argmax(axis = 0 )   # column wise

array([1, 0, 1, 0, 1], dtype=int64)

In [43]:
# .argmax() gives max element index in a particular axis
two.argmax(axis = 1 )   # row wise

array([3, 0], dtype=int64)

In [44]:
# .argmin() gives min element index in a particular axis
two.argmin(axis = 0)   # column wise

array([0, 1, 0, 1, 0], dtype=int64)

In [45]:
# .argmin() gives min element index in a particular axis
two.argmin(axis = 1)   # row wise

array([0, 1], dtype=int64)

In [46]:
# gives array of index of asceending order of element
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [47]:
# gives array of index of asceending order of element
a = two.argsort()
a

array([[0, 4, 2, 1, 3],
       [1, 3, 2, 4, 0]], dtype=int64)

In [48]:
Df = pd.DataFrame(a) # for fun
Df

0  1  2  3  4
0  0  4  2  1  3
1  1  3  2  4  0

In [49]:
pd.Series(two.argmax(axis=0)) # for fun

0    1
1    0
2    1
3    0
4    1
dtype: int64

# NumPy Operations : 

In [50]:
x = [[1,2,3,],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
y = [[1,2,1],[4,0,6],[8,1,0]]
ar2 = np.array(y)
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [53]:
# Sum
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [54]:
# Multiply
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [56]:
# square root
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [57]:
# square
np.square(ar)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [60]:
# find the item > 5
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [61]:
# counting non zero element
np.count_nonzero(ar)

8

In [62]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [63]:
import sys

In [66]:
py_ar = [0,4,55,2]

In [67]:
np_ar = np.array(py_ar)

In [69]:
sys.getsizeof(1)*len(py_ar)

112

In [70]:
np_ar.itemsize * np_ar.size

16

In [72]:
np_ar.tolist()

[0, 4, 55, 2]